service:
  name: ${self:custom.serviceName}

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: ${env:REGION}
  # profile: ${env:PROFILE}
  environment:
    JWKS_URI: ${ssm:/${self:custom.serviceName}/${env:STAGE}/JWKS_URI~true}
    AUDIENCE: ${ssm:/${self:custom.serviceName}/${env:STAGE}/AUDIENCE~true}
    TOKEN_ISSUER: ${ssm:/${self:custom.serviceName}/${env:STAGE}/TOKEN_ISSUER~true}
    NSOLID_LICENSE_KEY: ${ssm:/${self:custom.serviceName}/${env:STAGE}/NSOLID_LICENSE_KEY~true}

custom:
  serviceName: fii-auth
  stage: ${opt:stage, self:custom.defaultStage}
  defaultStage: dev
  stages:
    - ${opt:stage}
    - dev
    - integration
    - production

functions:
  auth:
    handler: src/handlers/authorizer/index.default
    cors: true
    events:
      - http:
          path: /auth
          method: post
  health:
    handler: src/handlers/healthCheck/index.default
    cors: true
    events:
      - http:
          path: /health
          method: get
          authorizer:
            name: health-authorizer
            arn: arn:aws:lambda:us-east-1:568614285549:function:fii-auth-dev-auth
            identitySource: method.request.header.Authorization
            resultTtlInSeconds: 0

resources:
  - ${file(./resources/FailResponse.yml)}
  - ${file(./resources/GatewayResponse.yml)}
  - ${file(./resources/CognitoUserPoolClient.yml)}
  - ${file(./resources/CognitoUserPool.yml)}

Outputs:
  UserPoolId:
    Value:
      Ref: CognitoUserPool

  UserPoolClientId:
    Value:
      Ref: CognitoUserPoolClient
